# Generated by Django 4.1.7 on 2023-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
