# Generated by Django 4.1.7 on 2023-04-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_magazine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
